_wandb:
    value:
        cli_version: 0.21.0
        e:
            cqmz51cyfu2bl0m2ya1tkc4mm5ysp2ww:
                codePath: lstm_sweeps.ipynb
                codePathLocal: lstm_sweeps.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "329313026048"
                email: toby.safie@gmail.com
                executable: c:\Users\tobys\anaconda3\envs\star-pinn\python.exe
                host: Tobias_Lenovo
                memory:
                    total: "14806552576"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\tobys\Downloads\GBM-ML-main\GBM-ML-main\lstm_sweeps.ipynb
                python: CPython 3.10.18
                root: c:\Users\tobys\Downloads\GBM-ML-main\GBM-ML-main
                startedAt: "2025-08-02T15:27:00.851641Z"
                writerId: cqmz51cyfu2bl0m2ya1tkc4mm5ysp2ww
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 16
dropout:
    value: 0
hidden_dim:
    value: 32
input_dim:
    value: 14
latent_dim:
    value: 64
learning_rate:
    value: 0.00022
num_epochs:
    value: 15
num_layers:
    value: 3
