_wandb:
    value:
        cli_version: 0.21.0
        e:
            h9qb9e8vshh1u2l6wa3a97bu2rhxeym6:
                codePath: lstm_sweeps.ipynb
                codePathLocal: lstm_sweeps.ipynb
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "2022669545472"
                        used: "1077390991360"
                email: toby.safie@gmail.com
                executable: c:\Users\tobys\miniconda3\envs\star-pinn\python.exe
                git:
                    commit: c44fb4136294a80aafff488b29e2faaa3f070805
                    remote: https://github.com/tobiassafie/GBM-ML-LSTM.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-a306856b-3d1f-329a-4622-5e45cf6837bb
                host: MAUMAU
                memory:
                    total: "68407418880"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\tobys\Desktop\GBM-ML-LSTM\lstm_sweeps.ipynb
                python: CPython 3.10.18
                root: c:\Users\tobys\Desktop\GBM-ML-LSTM
                startedAt: "2025-08-06T20:52:52.874758Z"
                writerId: h9qb9e8vshh1u2l6wa3a97bu2rhxeym6
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 16
dropout:
    value: 0.4
hidden_dim:
    value: 16
input_dim:
    value: 14
latent_dim:
    value: 64
learning_rate:
    value: 1.4979036502949324e-06
num_epochs:
    value: 10
num_layers:
    value: 2
