wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.1
hidden_dim:
  value: 256
input_dim:
  value: 14
latent_dim:
  value: 64
learning_rate:
  value: 0.000928629869942217
num_epochs:
  value: 7
num_layers:
  value: 2
