_wandb:
    value:
        cli_version: 0.21.0
        e:
            05hlnek74gglqiegloss3x99phkt8j08:
                codePath: encode_sweeps.ipynb
                codePathLocal: encode_sweeps.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "328806875136"
                email: toby.safie@gmail.com
                executable: c:\Users\tobys\anaconda3\envs\star-pinn\python.exe
                host: Tobias_Lenovo
                memory:
                    total: "14806552576"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\tobys\Downloads\GBM-ML-main\GBM-ML-main\encode_sweeps.ipynb
                python: CPython 3.10.18
                root: c:\Users\tobys\Downloads\GBM-ML-main\GBM-ML-main
                startedAt: "2025-08-01T00:29:04.415488Z"
                writerId: 05hlnek74gglqiegloss3x99phkt8j08
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 16
dropout:
    value: 0.1
learning_rate:
    value: 0.0019627084924675555
model_dim:
    value: 32
num_epochs:
    value: 50
num_heads:
    value: 4
num_layers:
    value: 2
reduced_dim:
    value: 1024
