wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0
hidden_dim:
  value: 512
input_dim:
  value: 14
latent_dim:
  value: 64
learning_rate:
  value: 0.000810370320436343
num_epochs:
  value: 10
num_layers:
  value: 2
