wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5
hidden_dim:
  value: 64
input_dim:
  value: 14
latent_dim:
  value: 64
learning_rate:
  value: 4.187040148775177e-06
num_epochs:
  value: 7
num_heads:
  value: 4
num_layers:
  value: 2
