wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.4
hidden_dim:
  value: 16
input_dim:
  value: 14
latent_dim:
  value: 64
learning_rate:
  value: 1.4979036502949324e-06
num_epochs:
  value: 10
num_layers:
  value: 2
