wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.3
hidden_dim:
  value: 128
input_dim:
  value: 14
latent_dim:
  value: 16
learning_rate:
  value: 0.00022
num_epochs:
  value: 15
num_layers:
  value: 3
