_wandb:
    value:
        cli_version: 0.21.0
        e:
            83hti72ag481fwciqj97p5f3bq5snrbn:
                codePath: lstm_sweeps.ipynb
                codePathLocal: lstm_sweeps.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "331573198848"
                email: toby.safie@gmail.com
                executable: c:\Users\tobys\anaconda3\envs\star-pinn\python.exe
                git:
                    commit: ffc6b592b2a141d66ba6bd711f7466a235bca0b5
                    remote: https://github.com/tobiassafie/GBM-ML-LSTM.git
                host: Tobias_Lenovo
                memory:
                    total: "14806552576"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\tobys\OneDrive\Desktop\GBM-ML-LSTM\lstm_sweeps.ipynb
                python: CPython 3.10.18
                root: c:\Users\tobys\OneDrive\Desktop\GBM-ML-LSTM
                startedAt: "2025-08-06T16:54:24.355974Z"
                writerId: 83hti72ag481fwciqj97p5f3bq5snrbn
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 16
dropout:
    value: 0.2
hidden_dim:
    value: 64
input_dim:
    value: 14
latent_dim:
    value: 32
learning_rate:
    value: 0.00014669145779581635
num_epochs:
    value: 5
num_layers:
    value: 2
