wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.2
hidden_dim:
  value: 64
input_dim:
  value: 14
latent_dim:
  value: 32
learning_rate:
  value: 0.0007629159899094961
num_epochs:
  value: 15
num_layers:
  value: 2
